/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/scene.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials["Material.003"]}
        position={[-0.053, 0.112, -0.018]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials["Material.002"]}
        position={[-0.053, 0.112, -0.018]}
      />
      <group position={[-0.1, 0.119, -0.015]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_1.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_2.geometry}
          material={materials["Material.001"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials["Material.004"]}
        position={[-0.1, 0.119, -0.015]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={nodes.Cube003.material}
        position={[-0.1, 0.119, -0.015]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={materials["Material.009"]}
        position={[-0.127, 0.255, 0.321]}
        scale={[0.627, 0.488, 0.415]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={materials["Material.007"]}
        position={[-0.669, 0.352, 0.332]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.057, -0.382, -0.397]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane004.geometry}
        material={nodes.Plane004.material}
        position={[0.304, 0.331, 0.307]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.057, -0.382, -0.397]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane005.geometry}
        material={materials["Material.010"]}
        position={[-0.231, 0.284, 0.152]}
        rotation={[0, 0, -Math.PI]}
        scale={[0.377, 0.699, 0.348]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane006.geometry}
        material={materials["Material.008"]}
        position={[0.39, 0.348, 0.318]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.057, -0.382, -0.397]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials["Material.005"]}
        position={[0.339, 0.314, -0.279]}
        scale={[0.201, 0.176, 0.204]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials["Material.006"]}
        position={[0.339, 0.314, -0.279]}
        scale={[0.201, 0.176, 0.204]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane007.geometry}
        material={nodes.Plane007.material}
        position={[0.568, -0.028, -1.337]}
        scale={[8.907, 1, 10.06]}
      />
    </group>
  );
}

useGLTF.preload("/scene.glb");
